# Phase 4 — List Elicitation

`plan_benzon.md` Part 4 / `plan_benzon_implementation.md` Phase 4. New construct: `variety`
("how varied are the items in a generated list?"), plus a second, per-item check that reuses
the existing `confidence` machinery unchanged rather than inventing anything new for it.

**Dataset** (`vconf/benzon_data.py`'s `load_list_elicitation_items`): 5 category keywords drawn
from Benzon's own concrete/abstract and Great-Chain-of-Being vocabulary — `animals`, `plants`,
`minerals`, `concrete objects`, `abstract concepts` — each turned into a plain generation
prompt (`prompts.LIST_ELICITATION_TEMPLATE`, `"Give me a list of {n} {category}."`,
`n=20`), not a fixed classification target: nothing about "give me 20 animals" is knowable
before the model answers — which twenty it picks is exactly the open question this phase
studies.

**Two self-reports, two ground truths, deliberately asymmetric in design cost:**

- **`variety`** (list-level) — a new `SentimentSpec` (`sentiment.VARIETY`). Ground truth:
  `activations.list_embedding_variety` — mean pairwise cosine distance between the list's own
  parsed items' pooled hidden states (`activations.pooled_hidden_state`), reusing the loaded
  model's own final-layer representations as the embedding source (no external embedding model
  exists anywhere in this repo, and none is needed).
- **Per-item category-membership `confidence`** — deliberately *not* a new sentiment or a new
  batched-response parser. `plan_benzon.md`'s own step 3 left the elicitation shape open
  ("batched... versus one Phase-1 call per item... default to batched; fall back to per-item
  only if batched proves unreliable to parse") — this notebook goes straight to **per-item**:
  each parsed list item becomes its own synthetic `(QuestionItem, Trial)` pair
  (`question="Name a specific example of {category}."`, `answer=item`), run through the
  existing `pipeline.run_phase1` with `sentiment=CONFIDENCE` completely unmodified. Ground
  truth here *can* be external and checkable (`ground_truth.ListItemCategoryMembership`, a
  WordNet hypernym-membership test) without repeating Phase 1's original commitment/nuance
  mistake — what's being checked is the model's own *generated choice* (did it pick a genuine
  example, or a borderline/wrong one — e.g. listing a whale under "fish"?), not a fact about a
  pre-selected question target that would need the answer known before generation.

**Phase 0 is genuinely different here.** Every other phase's Phase 0 bakes confidence
instructions into the prompt (`prompts.build_phase0_prompt`) because the model is meant to
self-report *at generation time* too. List elicitation doesn't want that — Phase 0 should
produce nothing but the plain list — so this notebook bypasses `run_phase0` entirely for the
generation step (a small inline `generate_list` helper below) and only reuses `run_phase1`
(fully generic over `trial.question`/`trial.answer` regardless of sentiment) for both
self-reports.

**Gate**: a deliberately uniform constructed list (20 near-duplicate items) and a deliberately
diverse one should visibly separate on both `variety`'s self-report and its embedding-distance
ground truth — included directly as a cell below, so the spot-check is reproducible, not just
something eyeballed once and noted.

In [1]:
import copy
import json
import os
import pathlib
import sys
from dataclasses import replace

import numpy as np
import pandas as pd

ROOT = next(p for p in [pathlib.Path.cwd(), *pathlib.Path.cwd().parents] if (p / "vconf").is_dir())
sys.path.insert(0, str(ROOT))

HERE = pathlib.Path.cwd()
with open(HERE / "config.json") as f:
    MODEL_CONFIG = json.load(f)
MODEL_NAME = MODEL_CONFIG["model"]
os.environ["VCONF_MODEL"] = MODEL_NAME
CACHE_DIR = HERE / "cache" / MODEL_NAME
OUT_DIR = HERE / "out" / MODEL_NAME
FIGS_DIR = OUT_DIR / "figs"
CACHE_DIR.mkdir(parents=True, exist_ok=True)
FIGS_DIR.mkdir(parents=True, exist_ok=True)
TRIAL_LOG_PATH = CACHE_DIR / "trial.json"
CONSTRUCT_PATH = CACHE_DIR / "construct.json"
SCALE = MODEL_CONFIG.get("scale", {})

from vconf import activations
from vconf import notebook as nb

_run_config = nb.run_config


def _run_config_with_overrides(base="gemma-categorical", **overrides):
    cfg = _run_config(base, **overrides)
    if MODEL_CONFIG.get("attn_implementation"):
        cfg = cfg.scaled(attn_implementation=MODEL_CONFIG["attn_implementation"])
    return cfg


nb.run_config = _run_config_with_overrides
from vconf import data as datamod
from vconf import ground_truth as GT
from vconf import metrics as M
from vconf import pipeline
from vconf.prompts import parse_list_items
from vconf.sentiment import CONFIDENCE, VARIETY, VARIETY_DEFINED

cfg = nb.run_config("gemma-categorical", dataset="benzon:list_elicitation", name="list-elicitation")
print(nb.describe(cfg))

profile          : reduced
model            : Qwen/Qwen2.5-7B-Instruct (28 layers)
sentiment        : confidence  (ground truth: correctness)
prompt / dataset : categorical / benzon:list_elicitation
layer sweep      : (0, 5, 11, 16, 22, 27)
trial counts     : {'steering': 24, 'patching': 24, 'noising': 32, 'swap': 24, 'attention': 24}
activation set   : 300   calibration set: 40
chat template    : True   attention impl: None
NOTE             : reduced profile — procedures, prompts, positions and
                   metrics follow the manual exactly, but the model and the
                   sample sizes are smaller than the paper's, so the numbers
                   here are not expected to match its reported values.

## Dataset

One `QuestionItem` per category — the question *is* the generation prompt itself.

In [2]:
items = datamod.load_dataset_items("benzon:list_elicitation", limit=SCALE.get("list_elicitation"))
print(f"{len(items)} category keywords")
pd.DataFrame([{"qid": i.qid, "question": i.question, "synset": i.meta["synset"]} for i in items])

5 category keywords

,qid,question,synset
0,list_0,Give me a list of 20 animals. Answer with just...,animal.n.01
1,list_1,Give me a list of 20 plants. Answer with just ...,plant.n.02
2,list_2,Give me a list of 20 minerals. Answer with jus...,mineral.n.01
3,list_3,Give me a list of 20 concrete objects. Answer ...,physical_entity.n.01
4,list_4,Give me a list of 20 abstract concepts. Answer...,abstraction.n.06

In [3]:
loaded = nb.open_model(cfg, device_map=MODEL_CONFIG.get("device_map"))

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

## Phase 0 — plain list generation (no confidence instructions baked in)

`generate_list` bypasses `run_phase0`/`build_phase0_prompt` on purpose: those always move a
confidence-instruction block to the front of the prompt (every other sentiment wants the model
to self-report *at generation time*), which is exactly what a list-elicitation Phase 0
shouldn't ask for — just the list, nothing else. No position tracking is needed either (Phase
4 runs no causal intervention), so this skips `RenderedPrompt` entirely and calls `generate`
on a plain chat-templated string.

In [4]:
def generate_list(loaded, cfg, prompt_text, max_new_tokens=400):
    if cfg.use_chat_template:
        text = loaded.tokenizer.apply_chat_template(
            [{"role": "user", "content": prompt_text}], tokenize=False, add_generation_prompt=True
        )
    else:
        text = prompt_text
    enc = loaded.tokenizer(
        [text], return_tensors="pt", add_special_tokens=not cfg.use_chat_template
    ).to(loaded.device)
    out = loaded.model.generate(
        **enc, max_new_tokens=max_new_tokens, do_sample=False, temperature=None, top_p=None,
        top_k=None, repetition_penalty=1.0, pad_token_id=loaded.tokenizer.pad_token_id,
    )
    new_tokens = out[:, enc["input_ids"].shape[1]:]
    return loaded.tokenizer.decode(new_tokens[0], skip_special_tokens=True).strip()


trials = []
for item in items:
    generated = generate_list(loaded, cfg, item.question)
    trial = pipeline.Trial(qid=item.qid, question=item.question, answer=generated)
    trials.append(trial)
    print(f"=== {item.meta['category']} ===")
    print(generated)
    print(f"parsed items: {parse_list_items(generated)}")
    print()

=== animals ===
1. Elephant
2. Giraffe
3. Zebra
4. Lion
5. Tiger
6. Bear
7. Wolf
8. Deer
9. Monkey
10. Penguin
11. Koala
12. Kangaroo
13. Crocodile
14. Snake
15. Horse
16. Camel
17. Duck
18. Owl
19. Fish
20. Butterfly
parsed items: ['Elephant', 'Giraffe', 'Zebra', 'Lion', 'Tiger', 'Bear', 'Wolf', 'Deer', 'Monkey', 'Penguin', 'Koala', 'Kangaroo', 'Crocodile', 'Snake', 'Horse', 'Camel', 'Duck', 'Owl', 'Fish', 'Butterfly']

=== plants ===
1. Rose
2. Sunflower
3. Orchid
4. Bamboo
5. Daisy
6. Peony
7. Iris
8. Fern
9. Jasmine
10. Lavender
11. Tomato
12. Pepper
13. Cactus
14. Ivy
15. Geranium
16. Chrysanthemum
17. Maple
18. Oak
19. Pine
20. Willow
parsed items: ['Rose', 'Sunflower', 'Orchid', 'Bamboo', 'Daisy', 'Peony', 'Iris', 'Fern', 'Jasmine', 'Lavender', 'Tomato', 'Pepper', 'Cactus', 'Ivy', 'Geranium', 'Chrysanthemum', 'Maple', 'Oak', 'Pine', 'Willow']

=== minerals ===
Quartz
Feldspar
Calcite
Mica
Gypsum
Halite
Pyrite
Sulfur
Talc
Bauxite
Chromite
Copper
Gold
Silver
Diamond
Graphite
Magnetite
Sphalerite
Zircon
parsed items: ['Quartz', 'Feldspar', 'Calcite', 'Mica', 'Gypsum', 'Halite', 'Pyrite', 'Sulfur', 'Talc', 'Bauxite', 'Chromite', 'Copper', 'Gold', 'Silver', 'Diamond', 'Graphite', 'Magnetite', 'Sphalerite', 'Zircon']

=== concrete objects ===
1. Car
2. Phone
3. Book
4. Pen
5. Chair
6. Table
7. Lamp
8. Sofa
9. Desk
10. Computer
11. Water Bottle
12. Watch
13. Key
14. Wallet
15. Notebook
16. Mug
17. Rug
18. Door
19. Window
20. Mirror
parsed items: ['Car', 'Phone', 'Book', 'Pen', 'Chair', 'Table', 'Lamp', 'Sofa', 'Desk', 'Computer', 'Water Bottle', 'Watch', 'Key', 'Wallet', 'Notebook', 'Mug', 'Rug', 'Door', 'Window', 'Mirror']

=== abstract concepts ===
1. Love
2. Freedom
3. Justice
4. Time
5. Knowledge
6. Power
7. Creativity
8. Reality
9. Emotion
10. Existence
11. Truth
12. Perception
13. Memory
14. Hope
15. Destiny
16. Intuition
17. Harmony
18. Responsibility
19. Courage
20. Balance
parsed items: ['Love', 'Freedom', 'Justice', 'Time', 'Knowledge', 'Power', 'Creativity', 'Reality', 'Emotion', 'Existence', 'Truth', 'Perception', 'Memory', 'Hope', 'Destiny', 'Intuition', 'Harmony', 'Responsibility', 'Courage', 'Balance']

## `variety` self-report — `VARIETY` vs. `VARIETY_DEFINED`, both via `run_phase1` unmodified

`run_phase1` builds its prompt generically from `trial.question`/`trial.answer` and
`cfg.sentiment` — it has no idea (and needs no idea) that `trial.answer` here is a list rather
than a single-fact answer, so swapping `sentiment` is the only change needed between variants.

A first run of this notebook found `VARIETY` saturating at "Highly varied" even for a
deliberately uniform constructed list — a logit-margin diagnostic traced this to the bare word
"near-duplicates" being read narrowly (literal string repetition only), not broadly (synonyms,
rephrasings, different breeds of the same animal). `VARIETY_DEFINED` is the same A/B pattern as
`MACHINE_COMMITMENT_DEFINED`/`NUANCE_DEFINED`: identical criterion, prefixed with an explicit
definition that spells out the broader reading. Both variants run here, side by side, on the
same trials.

In [5]:
VARIETY_OMS = {"variety": VARIETY, "variety_defined": VARIETY_DEFINED}
variety_cfg = replace(cfg, sentiment=VARIETY)  # kept for the ground-truth section below (sentiment-independent)

trials_by_om = {}
for name, spec in VARIETY_OMS.items():
    om_cfg = replace(cfg, sentiment=spec)
    om_trials = copy.deepcopy(trials)
    pipeline.run_phase1(loaded, om_trials, om_cfg)
    trials_by_om[name] = om_trials

for item_idx, item in enumerate(items):
    parsed = parse_list_items(trials[item_idx].answer)
    row = "   ".join(
        f"{name}={spec.classes[trials_by_om[name][item_idx].class_index]}"
        for name, spec in VARIETY_OMS.items()
    )
    print(f"{item.meta['category']:20s}: {row}  ({len(parsed)} parsed items)")

animals             : variety=Highly varied   variety_defined=Highly varied  (20 parsed items)
plants              : variety=Highly varied   variety_defined=Highly varied  (20 parsed items)
minerals            : variety=Highly varied   variety_defined=Highly varied  (19 parsed items)
concrete objects    : variety=Highly varied   variety_defined=Highly varied  (20 parsed items)
abstract concepts   : variety=Highly varied   variety_defined=Highly varied  (20 parsed items)

## `variety` ground truth — pooled hidden states over the parsed items

`activations.list_embedding_variety` parses each trial's generated list
(`prompts.parse_list_items`), pools each item's own hidden state
(`activations.pooled_hidden_state` — encoded standalone, not read live during the generation
that produced it), and takes the mean pairwise cosine distance between them
(`metrics.mean_pairwise_cosine_distance`).

In [6]:
variety_gt_by_qid = {trial.qid: activations.list_embedding_variety(trial, loaded) for trial in trials}

variety_df = pd.DataFrame({
    "category": [item.meta["category"] for item in items],
    "n_items": [len(parse_list_items(trial.answer)) for trial in trials],
    **{
        f"{name}_self_report": [spec.classes[t.class_index] for t in trials_by_om[name]]
        for name, spec in VARIETY_OMS.items()
    },
    **{
        f"{name}_value": [t.confidence for t in trials_by_om[name]]
        for name in VARIETY_OMS
    },
    "embedding_variety_gt": [variety_gt_by_qid[trial.qid] for trial in trials],
})
display(variety_df)
print(f"\nNote: n={len(items)} categories — far too small a sample for a meaningful "
      "correlation number; read this table by eye, not by rho.")

,category,n_items,variety_self_report,variety_defined_self_report,variety_value,variety_defined_value,embedding_variety_gt
0,animals,20,Highly varied,Highly varied,0.88,0.88,0.325026
1,plants,20,Highly varied,Highly varied,0.88,0.88,0.334441
2,minerals,19,Highly varied,Highly varied,0.88,0.88,0.300287
3,concrete objects,20,Highly varied,Highly varied,0.88,0.88,0.364058
4,abstract concepts,20,Highly varied,Highly varied,0.88,0.88,0.326069

Note: n=5 categories — far too small a sample for a meaningful correlation number; read this table by eye, not by rho.

## Per-item category-membership `confidence`

Every parsed item becomes its own synthetic `(QuestionItem, Trial)` pair —
`question="Name a specific example of {category}."`, `answer=item` — run through the
existing, completely unmodified `confidence` Phase-1 machinery. Ground truth:
`ground_truth.ListItemCategoryMembership`, a WordNet hypernym check against the category's
mapped synset (`benzon_data.LIST_ELICITATION_CATEGORIES`).

In [7]:
from vconf.data import QuestionItem

item_items, item_trials = [], []
for item, trial in zip(items, trials):
    for i, parsed in enumerate(parse_list_items(trial.answer)):
        item_items.append(QuestionItem(
            qid=f"{item.qid}_item{i}",
            question=f"Name a specific example of {item.meta['category']}.",
            meta={"category": item.meta["category"], "synset": item.meta["synset"], "example": parsed},
        ))
        item_trials.append(pipeline.Trial(
            qid=f"{item.qid}_item{i}",
            question=f"Name a specific example of {item.meta['category']}.",
            answer=parsed,
        ))

confidence_cfg = replace(cfg, sentiment=CONFIDENCE)
pipeline.run_phase1(loaded, item_trials, confidence_cfg)

membership_key = GT.ListItemCategoryMembership()
labels = membership_key.labels(item_items, item_trials)

item_df = pd.DataFrame({
    "category": [qi.meta["category"] for qi in item_items],
    "example": [qi.meta["example"] for qi in item_items],
    "confidence": [t.confidence for t in item_trials],
    "valid": [t.valid for t in item_trials],
    "is_genuine_member (WordNet)": labels,
})
display(item_df)

,category,example,confidence,valid,is_genuine_member (WordNet)
0,animals,Elephant,0.85,True,True
1,animals,Giraffe,0.85,True,True
2,animals,Zebra,0.85,True,True
3,animals,Lion,0.85,True,True
4,animals,Tiger,0.85,True,True
...,...,...,...,...,...
94,abstract concepts,Intuition,0.65,True,True
95,abstract concepts,Harmony,0.65,True,True
96,abstract concepts,Responsibility,0.65,True,True
97,abstract concepts,Courage,0.65,True,True
98,abstract concepts,Balance,0.65,True,True

In [8]:
valid_mask = item_df["valid"].to_numpy()
confidences = item_df.loc[valid_mask, "confidence"].to_numpy(dtype=float)
correct = item_df.loc[valid_mask, "is_genuine_member (WordNet)"].to_numpy(dtype=bool)

n_dropped = (~valid_mask).sum()
print(f"{n_dropped} item(s) dropped (unparseable/no WordNet noun sense)")
print(f"share of generated items that are genuine category members: {correct.mean():.1%}" if len(correct) else "no valid items")

if len(set(correct.tolist())) > 1:
    ece = M.expected_calibration_error(confidences, correct)
    auc = M.auroc(confidences, correct)
    print(f"ECE (confidence vs. genuine membership): {ece:.3f}")
    print(f"AUROC (confidence vs. genuine membership): {auc:.3f}")
else:
    print("every valid item landed on the same side (all genuine or all not) — "
          "ECE/AUROC need both classes present, so they're not computable on this run.")

0 item(s) dropped (unparseable/no WordNet noun sense)
share of generated items that are genuine category members: 93.9%
ECE (confidence vs. genuine membership): 0.149
AUROC (confidence vs. genuine membership): 0.560

## Gate — the constructed uniform-vs-diverse spot-check (`plan_benzon_implementation.md`)

> a deliberately uniform constructed list (e.g. five very similar items) and a deliberately
> diverse one should visibly separate on both the `variety` self-report and its ground truth.

Not model-generated — both lists are hand-constructed so the "should separate" claim is
checked against a known-uniform and a known-diverse case, not against whatever the model
happened to produce above. Both `VARIETY` and `VARIETY_DEFINED` are checked against the same
two lists, so this cell doubles as the actual A/B result: does spelling out "near-duplicate"
more broadly fix the collapse `VARIETY` showed here, or not?

In [9]:
uniform_list_text = "\n".join(f"{i + 1}. {name}" for i, name in enumerate([
    "A dog", "A puppy", "A canine", "A hound", "A pooch", "A mutt", "A doggy", "A pup",
    "A cur", "A mongrel", "A retriever", "A terrier", "A spaniel", "A collie", "A poodle",
    "A beagle", "A bulldog", "A labrador", "A dachshund", "A chihuahua",
]))
diverse_list_text = "\n".join(f"{i + 1}. {name}" for i, name in enumerate([
    "A mountain", "Justice", "An electron", "Jazz music", "A spreadsheet", "A volcano",
    "Freedom", "A hurricane", "A sonnet", "A telescope", "Loneliness", "A pyramid",
    "A symphony", "A whirlpool", "Democracy", "A comet", "A lighthouse", "Nostalgia",
    "A glacier", "A microchip",
]))

uniform_gt = None
diverse_gt = None
gate_rows = []
for name, spec in VARIETY_OMS.items():
    om_cfg = replace(cfg, sentiment=spec)
    uniform_trial = pipeline.Trial(qid=f"gate_uniform_{name}", question="Give me a list of 20 things.", answer=uniform_list_text)
    diverse_trial = pipeline.Trial(qid=f"gate_diverse_{name}", question="Give me a list of 20 things.", answer=diverse_list_text)
    pipeline.run_phase1(loaded, [uniform_trial, diverse_trial], om_cfg)

    if uniform_gt is None:  # ground truth doesn't depend on which sentiment ran Phase 1 — compute once
        uniform_gt = activations.list_embedding_variety(uniform_trial, loaded)
        diverse_gt = activations.list_embedding_variety(diverse_trial, loaded)

    gate_rows.append({
        "OM": name, "list": "uniform (near-duplicates)",
        "self_report": spec.classes[uniform_trial.class_index], "self_report_value": uniform_trial.confidence,
    })
    gate_rows.append({
        "OM": name, "list": "diverse (unrelated items)",
        "self_report": spec.classes[diverse_trial.class_index], "self_report_value": diverse_trial.confidence,
    })

gate_df = pd.DataFrame(gate_rows)
gate_df["embedding_variety_gt"] = gate_df["list"].map({
    "uniform (near-duplicates)": uniform_gt, "diverse (unrelated items)": diverse_gt,
})
display(gate_df)

# Per-OM separation, not an all-must-pass requirement — this is an A/B test (same
# spirit as Phases 1-3's "winner" semantics): the question is whether *any*
# wording clears the bar, not whether every candidate wording does.
om_separates = {}
for name in VARIETY_OMS:
    sub = gate_df[gate_df["OM"] == name].set_index("list")
    om_separates[name] = (
        sub.loc["diverse (unrelated items)", "self_report_value"] > sub.loc["uniform (near-duplicates)", "self_report_value"]
    )
    print(f"{'PASS' if om_separates[name] else 'FAIL'}  {name}: diverse list's self-reported variety exceeds the uniform list's")

gt_separates = diverse_gt > uniform_gt
print(f"{'PASS' if gt_separates else 'FAIL'}  diverse list's embedding-variety ground truth exceeds the uniform list's")

winning_om = next((name for name, ok in om_separates.items() if ok), None)
gate_passed = gt_separates and winning_om is not None
print(f"\n{'GATE PASSED' if gate_passed else 'GATE FAILED'}"
      f" — {f'{winning_om!r} separates uniform from diverse on both signals' if gate_passed else 'no OM separates uniform from diverse; debug before treating variety as validated'}")

,OM,list,self_report,self_report_value,embedding_variety_gt
0,variety,uniform (near-duplicates),Highly varied,0.88,0.209005
1,variety,diverse (unrelated items),Highly varied,0.88,0.332806
2,variety_defined,uniform (near-duplicates),Varied,0.62,0.209005
3,variety_defined,diverse (unrelated items),Highly varied,0.88,0.332806

FAIL  variety: diverse list's self-reported variety exceeds the uniform list's
PASS  variety_defined: diverse list's self-reported variety exceeds the uniform list's
PASS  diverse list's embedding-variety ground truth exceeds the uniform list's

GATE PASSED — 'variety_defined' separates uniform from diverse on both signals

**Interpretation.** The gate above is the phase's actual go/no-go check — a small, controlled
spot-check, not a claim about how well either `VARIETY` OM performs on real model-generated
lists in general (the n=5-category table earlier is real generations, but far too small a
sample to draw a statistical conclusion from). Whichever of `variety`/`variety_defined` passes
the gate — if either does — is the wording to keep; if neither does, the fix belongs in
`activations.pooled_hidden_state`/`metrics.mean_pairwise_cosine_distance` instead, since the
embedding-distance ground truth already separates these two constructed lists correctly on its
own — the open question this gate settles is only about the self-report side.

## Log every cell to `trial.json`

`variety`/`variety_defined` are specific to this dataset (list-level), so they're logged
under `dataset="list_elicitation"` rather than the general OM×GT set. The `rho` for the real
5-category run is exploratory only (n=5, noted above) — kept for the record, not treated as
validated the way the constructed gate is.

In [10]:
from vconf import trial_log as TL

records = [
    {
        "dataset": "list_elicitation", "om": name, "gt": "embedding_variety_gt",
        "rho": M.intrinsic_correlation(variety_df[f"{name}_value"].to_numpy(), variety_df["embedding_variety_gt"].to_numpy()),
        "n": len(variety_df),
    }
    for name in VARIETY_OMS
]
records.append({
    "dataset": "list_elicitation", "om": "confidence", "gt": "category_membership",
    "rho": M.intrinsic_correlation(confidences, correct.astype(float)),
    "n": len(confidences),
})

TL.upsert(records, path=TRIAL_LOG_PATH)
print(f"logged {len(records)} cells to {TRIAL_LOG_PATH}")

logged 3 cells to /home/stud_homes/s7846062/fatass/home/thesis/experiment/code_morph/notebooks_benzon/phase_0_calibration/cache/qwen/trial.json

/home/stud_homes/s7846062/fatass/home/thesis/experiment/code_morph/vconf/metrics.py:202: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return float(stats.spearmanr(x[mask], y[mask]).correlation)